export const tShirtBrands: string[] = [
  "ARROW",
  "JACK&JONES",
    "NIKE",
    "Adidas",
    "MUFTI",
    "Puma",
    "Under Armour",
    "Reebok",
    "LEVIS",
    "H&M",
    "Uniqlo",
    "Zara",
    "Gap",
    "Tommy Hilfiger",
    "Hollister",
    "Abercrombie & Fitch",
    "Calvin Klein",
    "Ralph Lauren",
    "Lacoste",
    "Supreme",
    "Gucci",
    "Prada",
    "Versace",
    "Armani",
    "Diesel",
    "Balmain",
    "Champion",
    "FILA",
    "Converse",
    "adda"
];

export const sellers: string[] = [
    'seller1',
    'seller2',
    'seller3',
    'seller4',
    'seller5',
    'seller6',
    'seller7',
    'seller8',
    'seller9',
    'seller10',
    'seller11',
    'seller12',
    'seller13',
    'seller14',
    'seller15',
    'seller16',
    'seller17',
    'seller18',
    'seller19',
    'seller20',
]